export const IS_GITHUB_PAGES = __GITHUB_PAGES__;
export const CAN_USE_ADVANCED_RUNTIME = !IS_GITHUB_PAGES;
export const GITHUB_REPOSITORY = __GITHUB_REPOSITORY__;
export const GITHUB_REPOSITORY_URL = __GITHUB_REPOSITORY_URL__;
